---
title: "Trigger Simulation"
output: html_document
date: "2023-09-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intro

In this document we simulate the trigger using historical IRI and historical VHI data.

```{r cars}
library(targets)
library(tidyverse)
library(gghdx)
library(gt)
gghdx()
tar_load(df_cropland_lte_vhi_threshold)
tar_load(df_iri_adm0)

vhi_thresh <- 0.35
area_thresh <-  0.25
iri_pbavg_thresh <- 0.45
```


Initial triggers:

1. Mean IRI probability below average ≥ 45
2. ≥ 25 % of cropland with VHI ≤ 0.25

```{r}

# tak max probability (bavg) across leadtimes
df_iri_adm0_max <- df_iri_adm0 %>% 
  group_by(
    across(starts_with("adm")), 
    predict_start_mo, seas
  ) %>% 
  summarise(
    across(.cols= c("mean","median"), ~max(.x/100))
  ) 

# filter to just relevant seasons
df_iri_adm0_max_relevant_season <- df_iri_adm0_max %>% 
  ungroup() %>% 
  filter(
    str_detect(seas,"MJJ|JJA|SON")
  ) 
```


## IRI

```{r}

df_iri_adm0_max_relevant_season %>% 
  group_by(across(starts_with("adm")),seas) %>% 
  mutate(
    flag_thresh = mean>=iri_pbavg_thresh
  ) %>% 
  # filter(flag_thresh) %>% 
  ungroup() %>% 
  select(adm0_es,Season=seas,mean) %>% 
  pivot_wider(
    names_from = adm0_es,
    values_from=mean
  ) %>% 
  gt::gt() %>% 
  gt::fmt_number(decimals=2) %>% 
  data_color(
    columns= `Guatemala`,
    rows = `Guatemala`>=iri_pbavg_thresh,
    palette= c(hdx_hex("tomato-light"), hdx_hex("tomato-dark"))
  ) %>% 
  data_color(
    columns= `El Salvador`,
    rows =`El Salvador`>=iri_pbavg_thresh,
    palette= c(hdx_hex("tomato-light"), hdx_hex("tomato-dark"))
  ) %>% 
  data_color(
    columns= `Nicaragua`,
    rows =`Nicaragua`>=iri_pbavg_thresh,
    palette= c(hdx_hex("tomato-light"), hdx_hex("tomato-dark"))
  ) %>% 
  data_color(
    columns= `Honduras`,
    rows =`Honduras`>=iri_pbavg_thresh,
    palette= c(hdx_hex("tomato-light"), hdx_hex("tomato-dark"))
  )

```

```{r}

fill_cols <- c(hdx_hex("grey-light"),hdx_hex("tomato-hdx"))

df_iri_adm0_max_relevant_season %>% 
  group_by(across(starts_with("adm")),seas) %>% 
  mutate(
    flag_thresh = mean>=iri_pbavg_thresh
  ) %>% 
  # filter(flag_thresh) %>% 
  ungroup() %>% 
  ggplot(
    aes(x= predict_start_mo,y=adm0_es,fill=mean)
  )+
  geom_tile(color="black")+
  binned_scale(
    aesthetics = "fill",
    scale_name = "custom", 
    palette = ggplot2:::binned_pal(scales::manual_pal(values = fill_cols)),
               guide = "bins",
               breaks = c(0,iri_pbavg_thresh,1), 
    
      )+
  scale_x_date(
    breaks= unique(df_iri_adm0_max_relevant_season$predict_start_mo),
    labels= unique(df_iri_adm0_max_relevant_season$seas)
  )+
  theme(
    axis.text.x = element_text(angle=90),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    legend.position="none"
  )
```

## VHI
```{r}

```

## IRI + VHI
```{r}

```

