---
title: "check_insivumeh_systems"
format: html
editor: visual
---

## Intro

Notebook to quickly look at new INSIVUMEH System run for June 2025 model.

```{r}


box::use(
  dplyr[...],
  forcats[...],
  glue[...],
  purrr[...],
  readr[...],
  stringr,
  tidyr,
  cumulus,
  lubridate[...],
  logger,
  sf,
  gt,
  gghdx,
  tidyr[...],
  ggplot2[...],
  gghdx,
  blastula[...],
  geoarrow[...],
  exactextractr[...]

)

gghdx$gghdx()

box::use(
  utils = ../src/utils/gen_utils,
  ../src/datasources/insivumeh,
)


# Get spatial AOI
AOI_GTM <- "Chiquimula"
gdf_adm1 <- cumulus$download_fieldmaps_sf(iso = "gtm",layer = "gtm_adm1")$gtm_adm1

gdf_gtm_aoi <- gdf_adm1 |> 
  filter(
    ADM1_ES %in% AOI_GTM
  ) |> 
  # leave in dissolve step in case we want to add more admins later
  # doesn't do anything with 1 admin
  group_by( 
    ADM0_ES
    ) |> 
  summarise(
    do_union = TRUE
  )


dir_insivumeh <- file.path(
  Sys.getenv("AA_DATA_DIR_NEW"),
  "private",
  "raw",
  "lac",
  "INSIVUMEH"
)

# The naming of the directories is confusing due to how they evolved/came to be

# this is the latest historical data run with 202506 model run
dir_update <-  file.path(
  dir_insivumeh,
  "202506_format"
)


# The rest are the "old format"
dir_old <-  file.path(
  dir_insivumeh,
  "old_format"
)

# even if they forlder is called new format --
# it's still part of the old model system. 
# we had to separate them beacuse of minor tweaks to the data structures
# which means they have different extents and cannot be stacked as 1 raster
# they also follow different filenaming conventions so have to be queried
# differently
dir_old_24 <- file.path(
  dir_insivumeh,
  "new_format",
  "2024"
)

dir_old_25 <- file.path(
  dir_insivumeh,
  "new_format",
  "2025"
)

# This has all the data from the old format run 1980-2023
r_old_lte_2023 <- insivumeh$load_ncdf_insivumeh(
  gdb = dir_old,
  wrap=F,
  file_rgx_pattern =  "\\d{4}.nc$"
  )


# Here is the old format data pattern for 2024
pattern_old_24 <- "\\d{4}.*nc$"

# read in raster
r_old_2024 <- insivumeh$load_ncdf_insivumeh(
  gdb = dir_old_24,
  wrap=F,
  file_rgx_pattern = pattern_old_24
  )

pattern_old_2025 <- ".*_(Feb|Mar|Apr|May|Jun|Jul)2025.*\\.nc$"
# Here is the old format data pattern for 2025
r_old_2025 <- insivumeh$load_ncdf_insivumeh(
  gdb = dir_old_25,
  wrap=F,
  file_rgx_pattern =pattern_old_2025
  )


# lets put the lists together so we can `map()` through zonal statistics
# separately - but all at once.
lr <- list(
  "old1" = r_old_lte_2023,
  "old2" =r_old_2024,
  "old3" = r_old_2025
)

# since new format has new extent, we just run the zonal statistics separtely
ldf <- map(lr,\(x){
  dft <- exact_extract(
    x = x,
    y = gdf_gtm_aoi,
    fun = "mean"
  )
  dft |> 
    pivot_longer(everything()) %>%
    separate(name, into = c("stat", "issued_date", "lt_chr"), sep = "\\.") %>%
    mutate(
      adm0_es = "Guatemala",
      issued_date = as_date(issued_date),
      leadtime = parse_number(lt_chr),
      valid_date = issued_date + months(leadtime),
      adm1_es = glue_collapse(AOI_GTM,sep =",")
    )
}
)

# df zonal stats old
dfz_old <- list_rbind(ldf)


# I'm not too concerned about primera right now, but will create it anywas
df_primera_insiv_old <- cumulus$seas5_aggregate_forecast(
  dfz_old,
  value ="value",
  valid_months = c(5:8),
  by = c("adm0_es","issued_date")
)


# more focusing on primera June moment for this notebook
df_postrera_insiv_old <- cumulus$seas5_aggregate_forecast(
  dfz_old,
  value ="value",
  valid_months = c(9:11),
  by = c("adm0_es","issued_date")
)

df_postrera_insiv_old$issued_date |> range()
```


```{r}

# No load the new system data 
r_update <- insivumeh$load_ncdf_insivumeh(
  gdb = dir_update,
  wrap=F,
  file_rgx_pattern = "^pronos_deterministic_forecast_"
  )

# Nice to double check all the years are there and we see 6 leadtimes per
tibble(
  bnames =names(r_update)
) |> 
  separate(col=bnames,sep = "\\.",into= c("date","lt")) |> 
  mutate(
    date = as_date(date),
  ) |> 
  filter(
    month(date)==6
  ) |> 
  group_by(
    yr = year(date)
  ) |> 
  summarise(n =n()) |> 
  print(n=34)


dfz_update <- exact_extract(
  x = r_update,
  y = gdf_gtm_aoi,
  fun = "mean"
)|> 
  pivot_longer(everything()) %>%
  separate(name, into = c("stat", "issued_date", "lt_chr"), sep = "\\.") %>%
  mutate(
    adm0_es = "Guatemala",
    issued_date = as_date(issued_date),
    leadtime = parse_number(lt_chr),
    valid_date = issued_date + months(leadtime),
    adm1_es = glue_collapse(AOI_GTM,sep =",")
  )


dfz_update |> 
  filter(
    month(issued_date)==6
  ) |> 
  group_by(
    yr = year(issued_date)
  ) |> 
  summarise(n =n()) |> 
  print(n=34)


# again dont really care about primera - but can leave in if we want
# to extend notebook analysis later
df_primera_insiv_update <- cumulus$seas5_aggregate_forecast(
  dfz_update,
  value ="value",
  valid_months = c(5:8),
  by = c("adm0_es","issued_date")
)


df_postrera_insiv_update <- cumulus$seas5_aggregate_forecast(
  dfz_update,
  value ="value",
  valid_months = c(9:11),
  by = c("adm0_es","issued_date")
)

# quick look at the forecast value from june 2025
df_postrera_insiv_update |> 
  filter(
    issued_date == as_date("2025-06-01")
  )

# quick look at the date range - correct
df_postrera_insiv_update$issued_date |> range()



```

## Postrera June Moment

```{r}
df_insiv_postrera_all<- bind_rows(
  mutate(df_postrera_insiv_update, source = "update"),
  mutate(df_postrera_insiv_old,, source ="old")
)

# Create one data set that just looks at June  from 1992 onwards
df_june_pub_gte1992 <- df_insiv_postrera_all |> 
  filter(leadtime ==3) |>
  filter(year(issued_date)>=1992)

# add anomalies on - note baseline is just 1992-current

df_june_pub_gte1992_w_anoms <- df_june_pub_gte1992|> 
  group_by(source) |> 
  mutate(
    avg = mean(value),
    abs_anom = value - avg,
    anom = abs_anom/(sd(value))
  ) |> 
  ungroup()
  

# raw anomaly (unstandardized)
df_june_pub_gte1992_w_anoms |> 
  ggplot(
    aes(x= issued_date, y= abs_anom, color = source, group = source)
  )+
  geom_point(alpha=0.3)+ 
  geom_line()+
  scale_x_date(date_breaks = "1 year",date_labels = "%Y")+
  labs(
    title = glue("INSIVUMEH Historical Postrera SON Forecasts For {AOI_GTM}"),
    subtitle = "June Publication Date"
    )+
  theme(
    axis.text.x = element_text(angle=90)
  )

# standardized anomaly
df_june_pub_gte1992_w_anoms |>
  ggplot(
    aes(x= issued_date, y= anom, color = source, group = source)
  )+
  geom_point(alpha=0.3)+ 
  geom_line()+
  scale_x_date(date_breaks = "1 year",date_labels = "%Y")+
  labs(
    title = glue("Standardized Precip Anomaly: {AOI_GTM}"),
    subtitle = "INSIVUMEH June Publication SON Forecast",
    caption = "Anomalies calculated on both records: 1992-2025"
    )+
  theme(
    axis.text.x = element_text(angle=90)
  )



```

```{r}
#| eval: false

# anomaly correlation
df_june_pub_gte1992_w_anoms |> 
  pivot_wider(
    id_cols = "issued_date",
    names_from = "source",
    values_from= "anom"
  ) |> 
  ggplot(
    aes(x= old, y= update)
  )+
  geom_point()
```

## Threshold by RP

```{r}


# calculate RPs and threshold
df_thresholded_1992_2022 <- df_june_pub_gte1992 |> 
  filter(year(issued_date)<=2022) |> 
  utils$threshold_var(var = "value", rp_threshold = 4,direction = -1, by ="source")
  


# Just copied this process over from the script where i do this to create the parquet
# it's overly complicated, but it works
rp_linear_funcs <- df_thresholded_1992_2022 |> 
  # filter(source =="update") |> 
        group_by(source,adm0_es,issued_month_label = month(issued_date,abbr=T,label = T),leadtime) |> 
        summarise(
          calc_empirical_rp_level = list(approxfun(rp_emp, value,method = "linear", rule =2,yright =Inf)),
          calc_empirical_rp = list(approxfun( value,rp_emp,method = "linear",rule =2))
        )

ldf_rp4_by_lt <- 
    rp_linear_funcs |> 
      group_by(source, adm0_es, leadtime,issued_month_label) |> 
      reframe(
        RP_empirical = 4,
        value_empirical = map_dbl(RP_empirical,calc_empirical_rp_level),
      )

# here we see the activation records if we calculate the RP based on 1992-2022.

df_june_pub_gte1992_w_anoms |>
  left_join(
    ldf_rp4_by_lt
  ) |> 
  mutate(
    flag = value<= value_empirical
  ) |> 
  ggplot(
    aes(x= issued_date, y= anom, color = source, group = source)
  )+
  geom_point(alpha=0.7, aes(color = flag))+ 
  geom_line()+
  scale_x_date(date_breaks = "1 year",date_labels = "%Y")+
  labs(
    title = glue("Standardized Precip Anomaly: {AOI_GTM}"),
    subtitle = "INSIVUMEH June Publication SON Forecast",
    caption = "Anomalies calculated on both records: 1992-2025"
    )+
  theme(
    axis.text.x = element_text(angle=90)
  )+
  facet_wrap(~source, nrow =2)
```


## Key Plot in Notebook
```{r}
df_june <- df_insiv_postrera_all |> 
  filter(leadtime ==3) 


df_thresholded_full_record <- df_june |> 
  filter(year(issued_date)<=2022) |> 
  utils$threshold_var(var = "value", rp_threshold = 4,direction = -1, by ="source")
  


# now we can linearly interpolate:
rp_linear_funcs <- df_thresholded_full_record |> 
  # filter(source =="update") |> 
        group_by(source,adm0_es,issued_month_label = month(issued_date,abbr=T,label = T),leadtime) |> 
        summarise(
          calc_empirical_rp_level = list(approxfun(rp_emp, value,method = "linear", rule =2,yright =Inf)),
          calc_empirical_rp = list(approxfun( value,rp_emp,method = "linear",rule =2))
        )


ldf_rp4_by_lt <- 
    rp_linear_funcs |> 
      group_by(source, adm0_es, leadtime,issued_month_label) |> 
      reframe(
        RP_empirical = 4,
        value_empirical = map_dbl(RP_empirical,calc_empirical_rp_level),
      )

df_june_pub_thresholded_from_1992 <- df_june_pub_gte1992_w_anoms |>
  left_join(
    ldf_rp4_by_lt
  ) |> 
  mutate(
    flag = value<= value_empirical
  )

df_june_pub_thresholded_from_1992 |> 
  filter(year(issued_date) ==2025) |> 
  select(value, threshold= value_empirical) 
  


df_june_pub_thresholded_from_1992 |> 
  ggplot(
    aes(x= issued_date, y= value, group = source)
  )+
  geom_point(alpha=0.7, aes(color = flag),show.legend = F)+ 
  scale_color_manual(values = c(hdx_hex("mint-hdx"),"tomato"))+
  geom_hline(data = ldf_rp4_by_lt |>
               rename(value = value_empirical),
             aes(yintercept=value) , color ="tomato", linetype ="dashed"
             )+
  geom_text(
    data= ldf_rp4_by_lt |>
               rename(value = value_empirical),aes(x= as_date("1998-06-01"),y= value-10,
                                                   label = glue("Threshold: {round(value,0)}")
                                                   ) , color = "tomato"
  )+
  # geom_hline(aes(yintecept = unique(value_empirical)))+
  geom_line()+
  scale_x_date(
    date_breaks = "1 year",
    date_labels = "%Y",
    limits = c(as_date("1992-01-01"),as_date("2025-12-01")),
    expand = c(0,0)
               )+
  labs(
    title =  glue("Historical  June Publication SON Forecasts From INSIVUMEH"),
    subtitle = glue("{AOI_GTM}"),
    caption = 
    "Thresholds calculated based on full historical record (up to 2022) available for each system.
    Old system: 1980-2022
    New System: 1992-2022"
    )+
  theme(
    axis.text.x = element_text(angle=90),legend.position = "none"
  )+
  facet_wrap(~source, nrow =2)
```


## Appendix

Some extra plots looking at fuller time series for old model data
```{r}


df_june_pub_gte1980 <- df_insiv_postrera_all |> 
  filter(leadtime ==3) 
  # filter(year(issued_date)>=1992)


df_june_pub_gte1980 |> 
  ggplot(
    aes(x= issued_date, y= value, color = source, group = source)
  )+
  geom_point()+ 
  geom_line()

df_june_pub_gte1980|> 
  group_by(source) |> 
  mutate(
    avg = mean(value),
    abs_anom = value - avg
  ) |> 
  ggplot(
    aes(x= issued_date, y= abs_anom, color = source, group = source)
  )+
  geom_point(alpha=0.3)+ 
  geom_line()+
  scale_x_date(date_breaks = "1 year",date_labels = "%Y")+
  labs(
    title = glue("INSIVUMEH Historical Postrera SON Forecasts For {AOI_GTM}"),
    subtitle = "June Publication Date"
    )+
  theme(
    axis.text.x = element_text(angle=90)
  )


df_june_pub_gte1980|> 
  group_by(source) |> 
  mutate(
    avg = mean(value),
    abs_anom = value - avg,
    anom = abs_anom/(sd(value))
  ) |> 
  ggplot(
    aes(x= issued_date, y= anom, color = source, group = source)
  )+
  geom_point(alpha=0.3)+ 
  geom_line()+
  scale_x_date(date_breaks = "1 year",date_labels = "%Y")+
  labs(
    title = glue("Standardized Precip Anomaly: {AOI_GTM}"),
    subtitle = "INSIVUMEH June Publication SON Forecast"
    )+
  theme(
    axis.text.x = element_text(angle=90)
  )

df_june_pub_gte1980|> 
  group_by(source) |> 
  mutate(
    avg = mean(value),
    abs_anom = value - avg,
    anom = abs_anom/(sd(value))
  ) |> 
  filter(year(issued_date)>1992) |> 
  ggplot(
    aes(x= issued_date, y= anom, color = source, group = source)
  )+
  geom_point(alpha=0.3)+ 
  geom_line()+
  scale_x_date(date_breaks = "1 year",date_labels = "%Y")+
  labs(
    title = glue("Standardized Precip Anomaly: {AOI_GTM}"),
    subtitle = "INSIVUMEH June Publication SON Forecast"
    )+
  theme(
    axis.text.x = element_text(angle=90)
  )

```



```{r}
df_postrera_old_anom_full_record <- df_postrera_insiv_old |> 
  filter(leadtime ==3) |>
  mutate(
    avg = mean(value),
    abs_anom = value - avg
  ) 
  
df_postrera_update_anom_full_record <- df_postrera_insiv_update |> 
  filter(leadtime ==3) |>
  mutate(
    avg = mean(value),
    abs_anom = value - avg
  ) 

df_insiv_postrera_all_anoms<- bind_rows(
  mutate(df_postrera_update_anom_full_record, source = "update"),
  mutate(df_postrera_old_anom_full_record, source ="old")
)
df_insiv_postrera_all_anoms |> 
  filter(leadtime ==3) |>
  filter(year(issued_date)>=1992) |> 
  ggplot(
    aes(x= issued_date, y= value, color = source, group = source)
  )+
  geom_point()+ 
  geom_line()

df_insiv_postrera_all_anoms |> 
  filter(leadtime ==3) |>
  filter(year(issued_date)>=1992) |> 
  mutate(
    avg = mean(value),
    abs_anom = value - avg
  ) |> 
  ggplot(
    aes(x= issued_date, y= abs_anom, color = source, group = source)
  )+
  geom_point(alpha=0.3)+ 
  geom_line()+
  labs(
    title = "SON Forecast Anomalies",
    subtitle = "Leadtime 3 month (July Publication)"
  )

  
```


