---
title: "Thresholds by LT table"
format:
  html:
    toc: true
    toc-depth: 3
    code-fold: true
    self-contained: true
    embed-resoures: true
    smooth-scroll: true
execute:
  include: true
  echo: true
  warning: false
  message: false
  eval: true
  results: "asis"
  out.width: "100%"
  code-fold: true
editor: visual
project:
  execute-dir: project
---

## Intro

Code takes output from `_targets.R` pipeline to create nicely formatted tables with thresholds for sharing.

```{r}
library(targets)
library(tidyverse)
library(gghdx)
library(gt)
library(here)
gghdx()

tar_load(df_all_thresholds_rp4,store = here("_targets"))
tar_load(df_cds_insivumeh_thresholds_rp4,store = here("_targets"))

ldf_ecmwf <- map(
  list("MARS_based"=df_all_thresholds_rp4,"CDs_based"=df_cds_insivumeh_thresholds_rp4),
  \(dft){
    dft_clean <- dft %>% 
      mutate(
        # quick little spelling fix for plotting
        window = str_to_title(
          case_when(
            window=="postera"~"postrera",
            .default =window
          )
        )
      )
    dft_clean %>% 
      split(.$forecast_source) %>% 
      map(\(dft_fcst){
        if(unique(dft_fcst$forecast_source)!="INSUVIMEH"){
          dft_fcst <- dft_fcst %>% 
            filter(
              !(adm0_es == "Guatemala" & 
                  lt %in% c(1:3))
            )
        }
        dft_fcst %>% 
          split(.$window)
        
        })
  }
)

```

## Primera

```{r}

# Prep Primera data
# Prep MARS data

primera_thresholds <- map(
  list(`MARs`=ldf_ecmwf$MARS_based$`ECMWF MARS`$Primera,
     `CDS` =ldf_ecmwf$CDs_based$`ECMWF CDs`$Primera,
     # doesnt actually matter which  for insiv
     `INSIV` =ldf_ecmwf$MARS_based$INSUVIMEH$Primera
  ), \(dft){
       dft %>% 
       mutate(
    pub_month_int = 5- lt,
    pub_month_chr = month(pub_month_int, label =T, abb=T),
    pub_month_lt = paste0(pub_month_chr," (", lt,")")
  ) %>% 
  select(
    adm0_es, 
    pub_month_lt,
    threshold = q_val
  )
  }
)
    

# merge mars and insiv for tabling
df_primera_thresholds_mars_long <- bind_rows(
  primera_thresholds$MARs,
  primera_thresholds$INSIV
)
df_primera_thresholds_cds_long <- bind_rows(
  primera_thresholds$CDS,
  primera_thresholds$INSIV
)

df_primera_table <- list(
  "MARS_SET"= df_primera_thresholds_mars_long,
  "CDS_SET"= df_primera_thresholds_cds_long
) %>% 
  map(
    \(dft){
      dft %>% 
      arrange(adm0_es) %>% 
      filter(
        !str_detect(pub_month_lt, "^Feb")
      ) %>% 
      pivot_wider(names_from = adm0_es,
                  values_from =threshold
      ) %>% 
      select(
        pub_month_lt, 
        `El Salvador`,
        Honduras,
        Nicaragua,
        Guatemala
      ) %>% 
      arrange(
        desc(parse_number(pub_month_lt))
      )
    }
  )

txt_footnote <- "Threshold calculations are made based on analysis of historical forecast data (1981-2022) to approximate a 1 in 4 year return period drought levels for rainfall over the entire season. Thresholds are calculated per country, leadtime, and forecast data source to minimize potential biases. Where possible national forecasts were used for this analysis and monitoring. Where no national forecasts were readily available, ECMWF seasonal forecasts/historical forecasts were used. <br><br><b> Note:</b> The national forecast provided by INSUVIMEH in Guatemala does not provide a forecast estimate for the month of publication, therefore for the final month of primera monitoring we use ECMWF data for all 4 countries"


# set colors for table/legend
ecmwf_cols <- c("El Salvador","Honduras","Nicaragua")
ecmwf_color <- hdx_hex("mint-light")
insuv_color <- hdx_hex("sapphire-light")


# make legend for table MARS data
gt_mars_legend <- data.frame(
  `Forecast Data Source` = "Forecast Data Source",
  ecmwf = "ECMWF (MARS)" ,
    insuv= "INSUVIMEH"

) %>% 
  gt(rowname_col = "Forecast Data Source") %>%  
  data_color(columns = "ecmwf", direction = "column",color=ecmwf_color) %>% 
  data_color(columns = "insuv", direction = "column",color=insuv_color) %>% 
  tab_options(
    column_labels.hidden = T
  ) %>% 
  as_raw_html()

gt_primera_mars_set <- df_primera_table$MARS_SET %>% 
  gt() %>% 
  fmt_number(decimals = 0) %>% 
  cols_label(
    pub_month_lt = html("Publication Month<br>(leadtime)")
  ) %>% 
  data_color(columns = ecmwf_cols, direction = "column",color=ecmwf_color) %>% 
   tab_style(
    style = cell_fill(color = insuv_color),
    locations = cells_body(
      columns = c("Guatemala"), 
      rows = 1:2
    )) %>% 
   tab_style(
    style = cell_fill(color = ecmwf_color),
    locations = cells_body(
      columns = c("Guatemala"), 
      rows = 3
    )) %>% 
  tab_footnote(footnote = html(txt_footnote)) %>% 
  tab_header(title = "Primera (MJJA 2024) Rainfall (mm) Monitoring Thresholds",
             subtitle = gt_mars_legend
             )

gt_cds_legend <- data.frame(
  `Forecast Data Source` = "Forecast Data Source",
  ecmwf = "ECMWF (CDs)" ,
    insuv= "INSUVIMEH"

) %>% 
  gt(rowname_col = "Forecast Data Source") %>%  
  data_color(columns = "ecmwf", direction = "column",color=ecmwf_color) %>% 
  data_color(columns = "insuv", direction = "column",color=insuv_color) %>% 
  tab_options(
    column_labels.hidden = T
  ) %>% 
  as_raw_html()

gt_primera_cds_set <- df_primera_table$CDS_SET %>% 
  gt() %>% 
  fmt_number(decimals = 0) %>% 
  cols_label(
    pub_month_lt = html("Publication Month<br>(leadtime)")
  ) %>% 
  data_color(columns = ecmwf_cols, direction = "column",color=ecmwf_color) %>% 
   tab_style(
    style = cell_fill(color = insuv_color),
    locations = cells_body(
      columns = c("Guatemala"), 
      rows = 1:2
    )) %>% 
   tab_style(
    style = cell_fill(color = ecmwf_color),
    locations = cells_body(
      columns = c("Guatemala"), 
      rows = 3
    )) %>% 
  tab_footnote(footnote = html(txt_footnote)) %>% 
  tab_header(title = "Primera (MJJA 2024) Rainfall (mm) Monitoring Thresholds",
             subtitle = gt_cds_legend
             )




gt_primera_cds_set
gt_primera_mars_set
```




## Postera

```{r}

# Prep Primera data
# Prep MARS data

postrera_thresholds <- map(
  list(`MARs`=ldf_ecmwf$MARS_based$`ECMWF MARS`$Postrera,
     `CDS` =ldf_ecmwf$CDs_based$`ECMWF CDs`$Postrera,
     # doesnt actually matter which  for insiv
     `INSIV` =ldf_ecmwf$MARS_based$INSUVIMEH$Postrera
  ), \(dft){
       dft %>% 
       mutate(
    pub_month_int = 9- lt,
    pub_month_chr = month(pub_month_int, label =T, abb=T),
    pub_month_lt = paste0(pub_month_chr," (", lt,")")
  ) %>% 
  select(
    adm0_es, 
    pub_month_lt,
    threshold = q_val
  )
  }
)
    

# merge mars and insiv for tabling
df_postrera_thresholds_mars_long <- bind_rows(
  postrera_thresholds$MARs,
  postrera_thresholds$INSIV
)
df_postrera_thresholds_cds_long <- bind_rows(
  postrera_thresholds$CDS,
  postrera_thresholds$INSIV
)

df_postrera_table <- list(
  "MARS_SET"= df_postrera_thresholds_mars_long,
  "CDS_SET"= df_postrera_thresholds_cds_long
) %>% 
  map(
    \(dft){
      dft %>% 
      arrange(adm0_es) %>% 
      filter(
            !str_detect(pub_month_lt, "^Sep|^May")
      ) %>% 
      pivot_wider(names_from = adm0_es,
                  values_from =threshold
      ) %>% 
      select(
        pub_month_lt, 
        `El Salvador`,
        Honduras,
        Nicaragua,
        Guatemala
      ) %>% 
      arrange(
        desc(parse_number(pub_month_lt))
      )
    }
  )

txt_footnote <- "Threshold calculations are made based on analysis of historical forecast data (1981-2022) to approximate a 1 in 4 year return period drought levels for rainfall over the entire season. Thresholds are calculated per country, leadtime, and forecast data source to minimize potential biases. Where possible national forecasts were used for this analysis and monitoring. Where no national forecasts were readily available, ECMWF seasonal forecasts/historical forecasts were used. <br><br><b> Note:</b> The national forecast provided by INSUVIMEH in Guatemala does not provide a forecast estimate for the month of publication, therefore for the final month of primera monitoring we use ECMWF data for all 4 countries"



gt_postrera_mars_set <- df_postrera_table$MARS_SET %>% 
  gt() %>% 
  fmt_number(decimals = 0) %>% 
  cols_label(
    pub_month_lt = html("Publication Month<br>(leadtime)")
  ) %>% 
  data_color(columns = ecmwf_cols, direction = "column",color=ecmwf_color) %>% 
   tab_style(
    style = cell_fill(color = insuv_color),
    locations = cells_body(
      columns = c("Guatemala"), 
      rows = 1:2
    )) %>% 
   tab_style(
    style = cell_fill(color = ecmwf_color),
    locations = cells_body(
      columns = c("Guatemala"), 
      rows = 3
    )) %>% 
  tab_footnote(footnote = html(txt_footnote)) %>% 
 tab_footnote(footnote = html(txt_footnote)) %>% 
  tab_header(title = "Postrera (SON 2024) Rainfall (mm) Monitoring Thresholds",
             subtitle = gt_mars_legend
             )

gt_postrera_cds_set <- df_postrera_table$CDS_SET %>% 
  gt() %>% 
  fmt_number(decimals = 0) %>% 
  cols_label(
    pub_month_lt = html("Publication Month<br>(leadtime)")
  ) %>% 
  data_color(columns = ecmwf_cols, direction = "column",color=ecmwf_color) %>% 
   tab_style(
    style = cell_fill(color = insuv_color),
    locations = cells_body(
      columns = c("Guatemala"), 
      rows = 1:2
    )) %>% 
   tab_style(
    style = cell_fill(color = ecmwf_color),
    locations = cells_body(
      columns = c("Guatemala"), 
      rows = 3
    )) %>% 
 tab_footnote(footnote = html(txt_footnote)) %>% 
  tab_header(title = "Postrera (SON 2024) Rainfall (mm) Monitoring Thresholds",
             subtitle = gt_cds_legend
             )

```

```{r}
gt_postrera_mars_set
```

```{r}
gt_postrera_cds_set
```
